// src/data.js
export const images = [
  { id: 1, title: 'Mountain View', description: 'A stunning view of the majestic mountains, perfect for nature enthusiasts who appreciate the serenity and beauty of the great outdoors', src: 'https://media.istockphoto.com/id/475797033/photo/sunlight-on-himalayan-mountain-range.jpg?s=612x612&w=0&k=20&c=GSMWx0pbDDFl-uhfVYC5mxc5XKZPOTjUs7Nvn6SjAx8=' },
  { id: 2, title: 'Ocean Breeze', description: 'Experience the calm and soothing ocean breeze, a peaceful escape from the hustle and bustle of everyday life.', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-SuZtnhEBIdrkhRUaxDElym5GGJgpOTSGG1MjA_YZzeYwfCV3F888HwR8gSbOaGYv058&usqp=CAU' },
  { id: 3, title: 'Forest Path', description: 'Take a peaceful walk through the dense forest path, where the sounds of nature surround you in every direction.', src: 'https://miro.medium.com/v2/resize:fit:1400/0*6lQ6FxwIWeJWhti6.jpg' },
  { id: 4, title: 'City Lights', description: 'The city comes alive at night with vibrant lights, offering a spectacular view that captures the essence of urban life.', src: 'https://media.istockphoto.com/id/531625878/photo/times-square.jpg?s=612x612&w=0&k=20&c=HVB1MVPGQEOHRML04NbAtfGbaDldRIPUGGwAljBDvi8=' },
  { id: 5, title: 'Desert Dunes', description: 'Explore the vast and mysterious desert dunes, where the golden sands stretch as far as the eye can see.', src: 'https://images.newscientist.com/wp-content/uploads/2020/11/11125043/crescendo-1200px_web.jpg' },
  { id: 6, title: 'Snowy Peaks', description: 'Snow-covered peaks rise majestically, offering a breathtaking view that is both tranquil and awe-inspiring.', src: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/snowy-peaks-bonnie-bruno.jpg' },
  { id: 7, title: 'Lush Valley', description: 'A lush green valley teeming with life, perfect for those who seek the beauty and tranquility of nature.', src: 'https://w0.peakpx.com/wallpaper/237/704/HD-wallpaper-rural-panorama-pretty-rural-hills-idilic-quality-grass-lush-valley-green-nature-field.jpg' },
  { id: 8, title: 'Sunset Glow', description: 'Witness the sky glow in vibrant hues during sunset, a magical moment that captures the beauty of the day’s end.', src: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/texas-sunset-m-magee-photography.jpg' },
  { id: 9, title: 'Autumn Leaves', description: 'The rich colors of autumn are on full display as leaves change, creating a mesmerizing and picturesque landscape.', src: 'https://homegrown.extension.ncsu.edu/wp-content/uploads/2021/11/Fall-Foliage-Changing-of-the-Leaves_Homegrown_Web-16x9-1.jpg' },
  { id: 10, title: 'Tranquil Lake', description: 'A tranquil lake with crystal clear water, offering a serene setting that is perfect for relaxation and reflection.', src: 'https://static.vecteezy.com/system/resources/previews/037/980/516/non_2x/ai-generated-of-tranquil-lake-surrounded-by-towering-mountains-and-lush-green-forests-the-image-captures-breathtaking-view-of-pristine-lake-reflecting-the-surrounding-landscape-ai-generated-free-photo.jpg' },
  { id: 11, title: 'Golden Fields', description: 'Golden fields stretch under the bright sun, a beautiful and expansive scene that captures the essence of the countryside.', src: 'https://media-cdn.tripadvisor.com/media/vr-splice-j/06/67/29/83.jpg' },
  { id: 12, title: 'Rocky Cliffs', description: 'Majestic rocky cliffs stand tall by the ocean, offering a dramatic and awe-inspiring view of nature’s raw power.', src: 'https://cdn.pixabay.com/photo/2022/04/09/18/21/rocky-coast-7122028_640.jpg' },
  
];
  